### PR TITLE
Update for March AMA session

### PR DESCRIPTION
**Pull request by iskerrett**
## Description

March AMA session web page.

### CODE REVIEW

**Comment by iskerrett** [comment]
@joepavitt can I get your help updating the image. I think it just needs a change to the date.

Also I noticed the dates are wrong on the webinar pages. I have entered March 9 on this page but it displays as March 8.  This is also happening for the webinar tomorrow.

**Comment by joepavitt** [comment]
Screenshot 2023-02-23 at 09 38 27
Screenshot 2023-02-23 at 09 38 31

hmmm... I can't reproduce that problem re: date

**Review by joepavitt — APPROVED** [review]

**Comment by iskerrett** [comment]
Here is a screenshot from my local machine today. 

Screenshot 2023-02-23 084513

**Comment by joepavitt** [comment]
well that is weird - may need to jump on a call/screenshare to fix that one, how does it show for you in production? www.flowfforge.com/webinars?

**Comment by iskerrett** [comment]
Not a priority right now. As long as it is working correctly on the live site.

**Pull request merged**
