### PR TITLE
Homepage Product CTAs

### PR DESCRIPTION
**Pull request by joepavitt**
Replacing the "Flexible Hosting Options" section on our homepage to remove confusion around offerings

### CODE REVIEW

**Comment by joepavitt** [comment]
Screenshot 2022-10-21 at 14 41 23

**Comment by knolleary** [comment]
Do we want to align the Open Source text to match on the newly updated Pricing page?

> We are an open-core company, try for free with deployment options including Docker and K8s

**Comment by joepavitt** [comment]
@knolleary done

**Comment by joepavitt** [comment]
Although, now the buttons don't align vertically...
Screenshot 2022-10-21 at 15 10 29

**Comment by knolleary** [comment]
If anything, jetison the 'we are an open core company' bit

**Comment by joepavitt** [comment]
done

**Review by knolleary — APPROVED** [review]

**Pull request merged**
