### PR TITLE
Added book a demo pictogram

### LINKED ISSUE #597: Book a Demo social media graphic
### Related Issue

_No response_

### Description

We want to start promoting on social media that CTA to 'Book a Demo'. Ideally we create something fairly unique with the FlowForge brand.  When we do the social media post we will add to the text the reasons to book a demo so these are not needed in the graphic.

### PR DESCRIPTION
**Pull request by Yndira-FlowForge**
## Description

Added book a demo pictogram

## Related Issue(s)

closes #597 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by Yndira-FlowForge** [comment]
I think we can improve this layout, will work on a proposal

**Comment by joepavitt** [comment]
> I think we can improve this layout, will work on a proposal

@Yndira-FlowForge layout for the page or the Pictogram?

**Comment by Yndira-FlowForge** [comment]
> @Yndira-FlowForge layout for the page or the Pictogram?

Layout. I understand we have a set of templates, but maybe add a short text, change the bg color of the calendar (red is too much for the eyes)... Or do you think is not necessary?

**Comment by joepavitt** [comment]
> Or do you think is not necessary?

Don't disagree at all, the red is configured from HubSpot though, who provide the Calendar widget, not in our own code. Just want to make sure we've got it recorded in an issue too, as we have a large backlog of stuff for the Website, and I don't want to be getting distracted with new work, when we have stuff that's been queued for a while.

**Comment by Yndira-FlowForge** [comment]
I opened this issue #669 and I understand it's not a priority ;)

**Review by ZJvandeWeg — APPROVED** [review]

**Review by iskerrett — APPROVED** [review]

**Pull request merged**
