### PR TITLE
Pricing

### PR DESCRIPTION
**Pull request by joepavitt**
**Desktop:**

https://user-images.githubusercontent.com/99246719/197178596-8eff4f6c-e5da-40ac-9ee7-758d412e3ea2.mov

**Mobile:**

https://user-images.githubusercontent.com/99246719/197178790-7b13e897-6494-4d05-b939-ddc051c943f1.mov

### CODE REVIEW

**Comment by joepavitt** [comment]
Need to finalise the taglines for each option

**Comment by joepavitt** [comment]
Latest version:

Screenshot 2022-10-21 at 11 50 57

**Comment by knolleary** [comment]
A slight rework of the Community box to propose. It felt a bit unbalanced to not have a sub heading in the box... WDYT?

image

**Comment by joepavitt** [comment]
I was fine with this, but then implemented and looked at it again. Now I'm not so sure. Whilst i does offer more balance, it's not part of the choice to be made by the user, which is what I'm trying to lead here.

In add "Open Source", I also feel like it then conflicts with the "self managed" side, as well, they're both self-managed.

Even though the "Community" and "Self Managed" are both self managed, the fact they're at different levels in the decision and on the screen, feels cleaner to me.

**Comment by knolleary** [comment]
@joepavitt good points well made.

I see you've removed the 'on your own' text which was the only other bit I wasn't a fan of as it read a bit Billy-No-Mates.

And TIL that `K8s` is the proper capitalisation and not `K8S` as I almost proposed.

**Review by knolleary — APPROVED** [review]

**Pull request merged**
