### PR TITLE
Add variants for button text

### PR DESCRIPTION
**Pull request by Yndira-FlowForge**
## Description

Implements the A/B test framework for #974

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt could you please check this out?

I've followed [this steps](https://posthog.com/docs/experiments/manual#testing-and-launching-your-experiment) trying to see if it's working, but I don't see the test version.

I even tried this
Screenshot 2023-07-17 at 14 58 46
but I still can't see the change... 

On local I see this message in the terminal:
`[eleventy-edge] WARN: No PostHog API Key - Falling back to A/B "control" content across the website`

And this in the chrome console:
Screenshot 2023-07-17 at 15 01 47

And I'm guessing this is normal on local.

But in the eleventy preview:
Screenshot 2023-07-17 at 15 02 56

And then, I was looking for the site apps in posthog and saw this:
Screenshot 2023-07-17 at 15 05 12

When I open the error message I see this line in there somewhere
```
"$active_feature_flags": [
      "ab-sign-up-button"
    ]
```
But I don't know if it's related, and I didn't want to disable it because I'm not sure what might stop working if I do.

**Comment by joepavitt** [comment]
Not normal on local, you should be able to run exactly same as prod in your local.

Will look into it tomorrow when I'm working

**Comment by joepavitt** [comment]
Spoken with Yndira about this, for some reason Netlify isn't pulling in the defined environment variables (even though Algolia still works?!).

The work around here is to add a `.env` into the website repo (this is already in `.gitignore`) so won't get pushed to GitHub. In this `.env` file then add:

```env
POSTHOG_APIKEY=<INSERT KEY HERE>
```

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett 
I've set up the experiment like this:

### Primary Metric: % Clicks > Sign up button in the top bar nav

- **Existing Conversion:** 1.6%
- **Target Conversion:** 6.6%
- **Recommended Duration:** 1 Day

### Configuration:

- **Key:**` ab-sign-up-button`
- **States:**
  - `control` - as we have it now (FREE TRIAL)
  - `get-started` - as proposed (GET STARTED)

**Review by iskerrett — APPROVED** [review]

**Pull request merged**
