### PR TITLE
Create getting-started-opcua-node-red

### PR DESCRIPTION
**Pull request by iskerrett**
August webinar promotion.

@joepavitt for some reason I am not able to preview this on my localhost so would you mind checking it for me. Please don't merge the PR since I still need to test the Hubspot/zoom integration.

### CODE REVIEW

**Comment by joepavitt** [comment]
Looking into it

**Comment by iskerrett** [comment]
> It seems to not show up on the netlify deploy preview either. Not sure what I have done wrong here. Any advice is appreciated.

sigh just figured it out. I forgot the .md extension.

**Comment by joepavitt** [comment]
that'll do it :)

**Comment by iskerrett** [comment]
> that'll do it :)

I should know better. It is not the first time I have done that.

**Comment by joepavitt** [comment]
image tile is also posted here: https://github.com/flowforge/website/issues/1012#issuecomment-1664047610

**Comment by joepavitt** [comment]
Did you also want to re-add the webinar banner at the very top of the site? Happy to add that in for you

**Comment by iskerrett** [comment]
> Did you also want to re-add the webinar banner at the very top of the site? Happy to add that in for you

That would be great, thanks

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
