### PR TITLE
analytics: Add HubSpot

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
To analyse how our content and pages work with our targeted users tracking is added from HubSpot.

The content type feature of HubSpot is not yet implemented, and will have to wait until a future iteration.

### CODE REVIEW

**Comment by joepavitt** [comment]
what does this give us that PH doesn't?

**Comment by ZJvandeWeg** [comment]
> what does this give us that PH doesn't?
Segmentation based on buyer persona.

**Comment by knolleary** [comment]
Am wary of adding multiple analytics - but taking it somewhat at face value that this is needed now. Will merge so we're capturing data asap, but would like a discussion on the different roles the tools play

**Comment by joepavitt** [comment]
> Segmentation based on buyer persona.

What does that actually mean in the context of HubSpot? PostHog enables segmentation by any of the features we record, and enables the definition of "Cohorts" which feature particular traits.

How is HubSpot defining a persona?

**Pull request merged**
