### PR TITLE
Re-style header into sections and ready for solutions dropdown

### LINKED ISSUE #319: Top Level Navigation Options
### Epic

_No response_

### Description

With @iskerrett coming onboard, I wanted to do a review of our top-level navigation options. We have a lot of content that is only accessible via Footer links, and whilst some of this may not be too valuable, it does add flavour and personality to our site, e.g. handbook/about us/team.

#### Header

Screenshot 2023-01-10 at 14 02 55

#### Footer

Screenshot 2023-01-10 at 14 03 07

### Acceptance Criteria

- [ ] Agree upon most important navigation links
- [ ] Produce designs to show alternatives
- [ ] Develop/Deploy alternatives

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

Splits the navigation header (in preparation for #412 adding /solutions/xxx). Driven by content/ideas in #319. Working across all screen sizes.

https://user-images.githubusercontent.com/99246719/222178928-9406eafe-f3e8-439e-9222-0b593b0e1647.mov

## Related Issue(s)

Closes #319 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [-] Suitable unit/system level tests have been added and they pass
 - [-] Documentation has been updated

### CODE REVIEW

**Review by iskerrett — COMMENTED** [review]
Not exactly sure I understand the change you made? However, the top menu now seems to be very crowded. It seems you have move in the margins so it spans a smaller amount of screen real estate.  Was this your intention?

**Comment by joepavitt** [comment]
> Not exactly sure I understand the change you made? However, the top menu now seems to be very crowded. It seems you have move in the margins so it spans a smaller amount of screen real estate. Was this your intention?

The screen recording is taken on a thinner screen in order to demonstrate the responsiveness of it.

In full-width it looks like this:

Screenshot 2023-03-01 at 16 34 43

**Comment by joepavitt** [comment]
In the design I had here: https://github.com/flowforge/website/issues/412#issuecomment-1441419099

I didn't have the "Docs" option actually, so we could remove that.

**Comment by iskerrett** [comment]
> > Not exactly sure I understand the change you made?
> 
> I've added the "Company" option per request, and added the respective options underneath that option too.
> 
> > The top menu now seems to be very crowded.
> 
> I've added the options you've asked for, it's about to get more crowded with "Solutions" too.
> 
> > It seems you have move in the margins so it spans a smaller amount of screen real estate.
> 
> I have in fact made the space taken up by the header much wider than was previously used. The screen recording is taken on a thinner screen in order to demonstrate the responsiveness of it.
> 
> In full-width it looks like this (including hte "solutions" option which I'm working on atm)
> 
> Screenshot 2023-03-01 at 16 34 43

This looks great.

**Comment by joepavitt** [comment]
> This looks great.

In that case, can you approve/merge the PR please :)

**Comment by joepavitt** [comment]
@iskerrett can I get a review on this please?

**Pull request merged**
