### PR TITLE
Updated messaging for the home page

### PR DESCRIPTION
**Pull request by iskerrett**
## Description

We want to update the FlowForge message. These changes reflect the new messaging.

## Related Issue(s)

https://github.com/flowforge/website/issues/366

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Appreciate this would have been discussed, but "DevOps for Node-RED" feels a lot weaker than "Run Node-RED in Production"?

We also don't even offer DevOps pipelines at the moment?

**Comment by joepavitt** [comment]
Also, with the addition of the teo new main features, now have duplicated images on our homepage which looks very unprofessional.

**Comment by joepavitt** [comment]
and typos on our homepage too:

Screenshot 2023-01-28 at 11 05 10

**Comment by iskerrett** [comment]
> Also, with the addition of the teo new main features, now have duplicated images on our homepage which looks very unprofessional.

It would be great if I can get helpe creating two new images. Can you help here?

Is there a reason the images appear to be blurred? It is very difficult to actually see NR in these images.

**Comment by iskerrett** [comment]
> Appreciate this would have been discussed, but "DevOps for Node-RED" feels a lot weaker than "Run Node-RED in Production"?
> 
> We also don't even offer DevOps pipelines at the moment?

Messaging is always very subjective. Run NR in Production doesn't really differentiate ourselves from everyone that run NR in production today.  The DevOps term conveys the qualities we can people to associate with using FlowForge. It also allows us to differentiate ourselves from other offerings.

**Comment by joepavitt** [comment]
> It would be great if I can get help creating two new images. Can you help here?

I can, but it'll be fairly low down on priority list at the moment.

> Is there a reason the images appear to be blurred? It is very difficult to actually see NR in these images.

The images definitely shouldn't be blurry. They're not on any devices I've tried to look at them on? What are you seeing?

**Comment by iskerrett** [comment]
Here is a screenshot of our home page from my computer. The images are blurring to me.


Screenshot 2023-02-01 152636

**Comment by joepavitt** [comment]
Are you referring to the solid grey/green/red blocking in the screenshots?

If so, that was intentional at the time, it was a quicker way of getting "screenshots" onto our homepage without the needs to ensure realistic names/data populating the platform before we took the screenshot.

**Comment by iskerrett** [comment]
Yes this is what I was referring too.

**Pull request merged**
