### PR TITLE
Iteration on /core-nodes nav

### PR DESCRIPTION
**Pull request by Yndira-FlowForge**
## Description

Implemented accordion lists for each group of nodes to enhance navigation.

## Related Issue(s)

#1144

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt, I think I need your help here. Let me know if you have a chance to go through it together, please 🙏

**Comment by joepavitt** [comment]
Going to really struggle for time today, _possibly_ available tomorrow.

**Comment by Yndira-FlowForge** [comment]
@iskerrett I implemented the accordions to the left nav. You mentioned you'd also like to add links in the main page of the core-nodes, here:
Screenshot 2023-09-22 at 15 18 17

But there are no pages to link them to, the titles of the node groups don't have a page of their own.

**Review by iskerrett — APPROVED** [review]
Looks good. Thank you for this improvement.

**Pull request merged**
