### PR TITLE
team: Add country flag to attributes

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
To show a bit more colour, and because it was fun to implement, the team
page now features a flag for each team member. Currently only NL and GB,
but someday hopefully more.

The allignment of the flag isn't quite right in the Y axis, and
potentially needs fixing.

### CODE REVIEW

**Comment by joepavitt** [comment]
I really like this idea, although not a fan of the 3d effect on the emoji's being used. I'll dig around to see if there are any 2d/flat alternatives and fit those in instead

**Comment by joepavitt** [comment]
Then toying with one of these two layouts. In both cases, I actually now don't mind the 3d icon.

Screenshot 2022-02-17 at 14 40 41

Screenshot 2022-02-17 at 14 41 32

**Comment by hardillb** [comment]
Second one as a preference from me (flag next to name)

**Comment by knolleary** [comment]
> Second one as a preference from me (flag next to name)

Me too.

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
