### PR TITLE
Image Pipeline: Faux image pipeline in development

### LINKED ISSUE #632: Development Pipeline Slowing: Image Pipeline
### Current Behavior

The local development pipeline (and production build time) are increasingly slowing, this hangs for sometime on the introduced Image pipeline work which massively improves performance when the site is running, but the development experience suffers.

Want to understand, is this slow because:
1. We have _too many_ images?
2. We have too many _big_ images?

Is there anything short term we can look at to improve this?

Raised by https://github.com/flowforge/website/issues/609 and https://github.com/flowforge/website/issues/621 referencing speed of recovery for the server.

### Expected Behavior

Ideally, smooth happy fast times when it comes to developing locally and iterating.

### Steps To Reproduce

_No response_

### Environment

_No response_

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

Fakes an image pipeline when in DEV_MODE (`npm run start`).
PROD_MODE (`npm run build`) still uses the same pipeline.

Images are naively copied over to the output directory, but a `<picture>` tag containing only one image (and two empty `<source>`'s is still used so the HTML is consistent.

This does mean there's a (subtle) difference between production and dev, so please make sure to use the Netlify build preview feature so sanity check ant new images @Yndira-FlowForge @ZJvandeWeg @joepavitt.

## Related Issue(s)

Fixes #632

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [x] Suitable unit/system level tests have been added and they pass
 - [-] Documentation has been updated

### CODE REVIEW

**Comment by joepavitt** [comment]
Any reason still in draft? Looks good to go to me?

**Comment by Pezmc** [comment]
@joepavitt Yes, those two commits above!

**Comment by Pezmc** [comment]
@joepavitt Is there a way to re-trigger the netlify build?

**Comment by joepavitt** [comment]
Seems it didn't, just kicked off manually.

**Pull request merged**
