### PR TITLE
Handle windows line endings when copying content from hb/docs

### PR DESCRIPTION
**Pull request by knolleary**
Handle Windows line endings when copying content from handbook/docs.

### CODE REVIEW

**Comment by joepavitt** [comment]
this still isn't fixing the issue unfortunately - this is what I had tried locally, but the particular file in question isn't collapsing the `---` as we'd expect

**Comment by knolleary** [comment]
Has the file in question been fixed to have the expected `---` at the start?

**Comment by joepavitt** [comment]
> Has the file in question been fixed to have the expected `---` at the start?

yes.

Although, looking in detail, it may be where I've mixed the line endings with my own editing:

```
---$
originalPath: marketing/webinars.md$
updated: 2023-01-31 13:45:55 +0700$
---$
---^M$
navTitle: Marketing^M$
---^M$
```

Unix line endings (\n or LF) as $ and Windows line endings (\r\n or CRLF) as ^M$.

**Comment by knolleary** [comment]
I've just merged https://github.com/flowforge/handbook/pull/206 to fix the file in git.

**Comment by knolleary** [comment]
Can confirm that has fixed it for me locally. A clean checkout of handbook + this branch builds correctly.

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
