### PR TITLE
analytics: Add Google Analytics

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
Currently we don't have any tracking at all on our website, and this
seemed like the fastest way to get started with it. Default Google
analytics script is used on each page now.

### CODE REVIEW

**Comment by hardillb** [comment]
I know Nick was looking at a different analytics provider that didn't track individual users and only provided aggregates for both flowforge.com and nodered.org. Let me see if I can find it before we pull the trigger on this.

**Comment by hardillb** [comment]
Found it, https://plausible.io/ is being loaded in the current flowforge.com

https://github.com/flowforge/website/blob/7166c431dbaef3ae8da6602ad473eaf1361ed489/src/_includes/layouts/base.njk#L24

**Comment by hardillb** [comment]
But I don't see the login details for it on 1Password, so we might have to ask Nick for them.

**Comment by ZJvandeWeg** [comment]
> But I don't see the login details for it on 1Password, so we might have to ask Nick for them.

Will do. Thanks for checking!

**Comment by knolleary** [comment]
I moved to Plausible on a free trial to see how it compared to GA. This includes the Node-RED site as well.

The number of page views we get on the NR site means it costs $50/month. But I think that is worth it.

I have moved the login details to the shared 1password vault.

**Pull request closed without merging**
