### PR TITLE
Update tagline in our OpenGraph image

### LINKED ISSUE #456: Update tagline in our corporate graphics
### Story

_No response_

### Description

 I need to update our social media profiles with the new messaging around DevOps for Node-RED. I would like to update the images we use on these accounts to change the take line from 'Collaborate, low-code, Integration & Automation' to 'DevOps for Node-RED'.  

I have attached mock-ups I created from the ai file on the Goole drive called Social Media Banners.ai. However, I can't actually change the ai file. Can someone help here.

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

- Updates our OpenGraph image with the "DevOps for Node-RED" tagline.

## Related Issue(s)

Closes #456

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [-] Suitable unit/system level tests have been added and they pass
 - [-] Documentation has been updated

### CODE REVIEW

**Review by iskerrett — COMMENTED** [review]
I am curious why you went with a different format to the one I submitted in #456. FWIW, In find in your version there is too much focus on 'DevOps for Node-RED'.

**Comment by joepavitt** [comment]
> I am curious why you went with a different format to the one I submitted in https://github.com/flowforge/website/issues/456

because thy use different fonts across each of the images, neither of the fonts are the one within our Branding Guidelines,  the text is not properly spaced & aligned, and for the second image the cloud b/g image is overlayed on top of the text

**Comment by joepavitt** [comment]
> In find in your version there is too much focus on 'DevOps for Node-RED'.

Very fair, will reduce the font size

**Comment by joepavitt** [comment]
> will reduce the font size 

done

**Comment by iskerrett** [comment]
> > I am curious why you went with a different format to the one I submitted in #456
> 
> because thy use different fonts across each of the images, neither of the fonts are the one within our [Branding Guidelines](https://flowforge.com/handbook/design/branding/), the text is not properly spaced & aligned, and for the second image the cloud b/g image is overlayed on top of the text

OK, I guess it would have been nice if you had pointed this out in the issue that I submitted.

FWIW, I would like to be the person updating the social media accounts. I am spending a fair bit of time there so it is important we don't overlap on the changes.

**Comment by joepavitt** [comment]
> OK, I guess it would have been nice if you had pointed this out in the issue that I submitted.

You'd mentioned they were mock ups - so I took them as such, not as the images you'd like to feature on our socials directly.

**Comment by joepavitt** [comment]
> FWIW, I would like to be the person updating the social media accounts. I am spending a fair bit of time there so it is important we don't overlap on the changes.

Was an easy thing for me to do, and the existing images were not up to a standard that I would want us publishing from a design perspective. I take your point though, and will leave that with you in the future.

**Comment by joepavitt** [comment]
@iskerrett are you okay with this now that i've reduced the font size for "DevOps for Node-RED"? If so, can you review/approve please?

**Comment by iskerrett** [comment]
I think I am missing something since I don't see any difference between the two images?  Can you post the new one directly into the comments.

**Comment by joepavitt** [comment]
If you go to the "Files Changed" tab in this window, you'll see them side by side:

Screenshot 2023-03-03 at 14 53 04

**Comment by iskerrett** [comment]
That version looks like the one I didn't like with the larger font. It also looks different from the version you posted on our twitter profile so I am a bit confused on what I am approving.

image

**Comment by joepavitt** [comment]
Good spot, that hasn't been properly updated since I reduced font size. Will sort that before I go away early next week.

**Comment by joepavitt** [comment]
Each different social media platform, and the Open Ggaph image all require/recommend different images sizes, so in the ai file, I have a bunch of Artboards with the respective sizes, and update across all of them for export to multiple jpgs

**Comment by joepavitt** [comment]
reduce the font-size and the gap slightly too - think it looks much better now, and is consistent with the others. Thought I had already reduces this font size when asking for the re-review, so apologies.

**Review by iskerrett — APPROVED** [review]

**Pull request merged**
